### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by elivin** [painassasin/jetstyle#5]
Общий итог: в целом очень хорошо, задача решена

Из моментов, на которые можно обратить внимание:

1. Версии образов в docker-compose лучше фиксировать, при выходе PostgreSQL версии 14 в текущем варианте контейнер не поднимется после обновления
2. Для DateTimeField можно использовать [auto_now_add](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.DateField.auto_now_add), чтобы не указывать вручную время при создании модели
3. Довольно много хардкода - хосты/порты баз, дебаг и т.д., хотя переменные окружения используются
4. В `TaskListViewSet.create()` зачем конструкция `if`, если указан параметр `raise_exception=True`? При наличии ошибок валидации будет блошено исключение (которое поймает DRF)
5. По поводу [entrypoint.sh](https://github.com/painassasin/jetstyle/blob/main/api/entrypoint.sh#L5) - при наличии ошибок в миграциях будет зацикливание, хотя контейнер будет считаться корректно поднятым. Можно посмотреть в сторону таких решений, как [wait-for-it](https://github.com/vishnubob/wait-for-it) (bash) и [wait-for](https://github.com/Eficode/wait-for) (sh)

**Comment by painassasin** [comment]
Спасибо, учту
